//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nevIepProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftwareProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SoftwareProduct()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public Nullable<long> Version { get; set; }
        public string Description { get; set; }
        public string Logo { get; set; }
        public string Picture { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public string CreatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
